### ISSUE TITLE
Concurrent exception while loading the relations

### ISSUE THREAD

**Issue by cbobed** [Rothamsted/rdf2neo#2]
I'm using the latest neo4j docker image. When loading the relationships (2nd stage), from time to time I get the following exception (see below). The process is finished without problems and only some edges are missed (it might not be critical depending on the dataset, but ...): 

28 Mar 2019 11:31:56.163 [cyRelLoad:190328-113154 64] [ERROR] (u.a.e.u.t.BatchProcessor,213): Error while running batch processor thread cyRelLoad:190328-113154 64: LockClient[164] can't wait on resource RWLock[NODE(43994), hash=7610
    88129] since => LockClient[164] <-[:HELD_BY]- RWLock[NODE(2974), hash=929193323] <-[:WAITING_FOR]- LockClient[163] <-[:HELD_BY]- RWLock[NODE(43994), hash=761088129]
456 org.neo4j.driver.v1.exceptions.TransientException: LockClient[164] can't wait on resource RWLock[NODE(43994), hash=761088129] since => LockClient[164] <-[:HELD_BY]- RWLock[NODE(2974), hash=929193323] <-[:WAITING_FOR]- LockClient[163]
     <-[:HELD_BY]- RWLock[NODE(43994), hash=761088129]
457         at org.neo4j.driver.internal.net.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:80)
458         at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:470)
459         at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:431)
460         at org.neo4j.driver.internal.net.SocketClient.receiveOne(SocketClient.java:196)
461         at org.neo4j.driver.internal.net.SocketClient.receiveAll(SocketClient.java:190)
462         at org.neo4j.driver.internal.net.SocketConnection.receiveAll(SocketConnection.java:203)
463         at org.neo4j.driver.internal.net.SocketConnection.sync(SocketConnection.java:157)
464         at org.neo4j.driver.internal.net.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:137)
465         at org.neo4j.driver.internal.net.pooling.PooledSocketConnection.sync(PooledSocketConnection.java:157)
466         at org.neo4j.driver.internal.NetworkSession.closeCurrentConnection(NetworkSession.java:370)
467         at org.neo4j.driver.internal.NetworkSession.syncAndCloseCurrentConnection(NetworkSession.java:349)
468         at org.neo4j.driver.internal.NetworkSession.close(NetworkSession.java:169)
469         at uk.ac.rothamsted.neo4j.utils.Neo4jDataManager.runSession(Neo4jDataManager.java:62)
470         at uk.ac.rothamsted.neo4j.utils.Neo4jDataManager.runCypher(Neo4jDataManager.java:86)
471         at uk.ac.rothamsted.rdf.neo4j.load.support.CyRelationLoadingHandler.accept(CyRelationLoadingHandler.java:92)
472         at uk.ac.rothamsted.rdf.neo4j.load.support.CyRelationLoadingHandler.accept(CyRelationLoadingHandler.java:24)
473         at uk.ac.ebi.utils.threading.BatchProcessor.lambda$handleNewTask$0(BatchProcessor.java:91)
474         at uk.ac.ebi.utils.threading.BatchProcessor.lambda$wrapTask$1(BatchProcessor.java:209)
475         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
476         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
477         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
478         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
479         at java.lang.Thread.run(Thread.java:748)

**Comment by marco-brandizi** [comment]
This isn't an actual error. There are multiple threads creating relations and sometimes the locks they create on the DB (I suppose over existing nodes data) cause potential deadlocks, which Neo4j detects and prevents by refusing to commit the transactions and returning these exceptions to the client. Our code intercepts them and fixes the problem by repeating the same transaction after a random delay, up to 10 attempts (it's based on this [generic utility](https://github.com/ISA-tools/jUtils/blob/master/jutils/src/main/java/uk/ac/ebi/utils/runcontrol/MultipleAttemptsExecutor.java)). This makes the transactions to go back to the server in a non-conflicting way, usually at the second attempt, I've never seen the tool to fail due to attempts exhaustion.

That said, 1) I will change the logger configuration at some point, to avoid those ugly messages 2) the mechanism causes some overhead, but usually not so much and I don't know any other way to realise parallelism in cases like this. 

Keeping the issue open, as a reminder to work on the logging.

**Comment by marco-brandizi** [comment]
@cbobed  This is embarrassing... The whole explanation I wrote in my comment above is NOW valid: I had prepared almost all the code to realise the re-attempt behaviour, but I had forgotten to actually make the last step of calling the component that deals with that logic!

So, you might have had non-committed relations, this change should fix your problems and will show less ugly messages when those relations clash and are recovered.

Sorry about that...
